# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- next-stable

jobs:
- job: Test_ceeling
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: true
    clean: true
    persistCredentials: true
  - script: |
      sudo apt install ruby-full
      sudo gem install ceedling
      pip install gcovr==4.1
      cd tests/drivers/imu/
      ceedling test:all
    displayName: 'Run a one-line script'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'tests/drivers/imu/build/artifacts/test/*.xml'
- job: print
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      echo Hi
      echo final
    displayName: 'test'
  