# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- next-stable
- 20*

pr:
- master
- next-stable
- 20*

variables:
- group: test_group

jobs:
- job: Test_ceeling
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: true
    clean: true
    persistCredentials: true
  - script: |
      set -e
      echo $(Build.SourceBranchName)
      var="\$(variablila_2022_R2)"
      echo $var
      echo ${!var}
      echo $(variablila_2022_R2)

    displayName: 'test1'
- job: print
  condition: eq(variables['Build.Reason'], 'PullRequest')
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      export BRANCH=$(branch)
      python test.py \
        dsf ssd

    displayName: 'test'
