# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    downloadBranch: 'master'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/next-stable') }}:
    downloadBranch: 'next-stable'

  variabilaTest: 'valoare'

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo $(downloadBranch)
    echo $(variabilaTest)

  displayName: 'Run a one-line script'

- publish: '$(Build.Repository.LocalPath)/test.txt'
  artifact: 'Xilinx'
