# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- staging/kuiper2.0

pr:
- staging/kuiper2.0

jobs:
- job: Kuiper_default
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 200
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: true
    clean: true
    persistCredentials: true
  - script: |
      echo "build image"
    displayName: 'Build image'

# trigger:
# - master
# - next-stable
# - 20*

# variables:
# - name: isMaster
#   value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
# - name: isNextStable
#   value:  $[eq(variables['Build.SourceBranch'], 'refs/heads/next_stable')]
# - name: isRelease
#   value: $[contains(variables['Build.SourceBranch'], 'refs/heads/20')]

# - ${{ if eq(variables['Build.Reason'], 'PullRequest')}}:
#   - name: branch
#     value: $(System.PullRequest.TargetBranchName)
# - ${{ else }}:
#   - name: branch
#     value: $(Build.SourceBranchName)

# jobs:
# - job: Test_ceeling
#   pool:
#     vmImage: ubuntu-latest
#   steps:
#   - checkout: self
#     fetchDepth: 1
#     submodules: true
#     clean: true
#     persistCredentials: true
#   - script: |
#       echo $(isMaster)
#       echo $(isNextStable)
#       echo $(isRelease)
# - job: print
#   pool:
#     vmImage: ubuntu-latest
#   steps:
#   - script: |
#       export BRANCH=$(branch)
#       python test.py \
#         dsf ssd

#     displayName: 'test'
