variables:

  ${{ if or(eq(variables['Build.SourceBranchName'], 'no-os_pr'), eq(variables['Build.SourceBranch'], 'next_stable')) }}:
    var5: $[variables['Build.SourceBranch']]
  ${{ elseif eq(variables['Build.Reason'], 'PullRequest') }}:
    var5: $[ format('refs/heads/{0}',replace(replace(variables['System.PullRequest.TargetBranch'], 'no-os_pr', 'no-os'), 'master', 'main')) ]
  ${{ else }}:
    var5: 'refs/heads/main'

trigger:
- master
- next-stable

jobs:
- job: Test_ceeling
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: true
    clean: true
    persistCredentials: true
  - script: |
      echo $(downloadBranch)
      echo $(Build.SourceBranchName)
      echo $(Build.Reason)
      echo $(System.PullRequest.TargetBranchName)
      echo $(var5)
      echo Salut
    displayName: 'Run a one-line script'
- job: print
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      echo Hi
      echo final
    displayName: 'test'
  