# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

trigger:
- master
- next-stable
- 20*

pr:
- master
- next-stable
- 20*

jobs:
- job: Test_ceeling
  pool:
    vmImage: ubuntu-latest
  container:
      image: tfcollins/libiio_debian_bookworm-ci:latest
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: true
    clean: true
    persistCredentials: true
  - script: |
      sphinx-build --version
      lsb_release -a
    displayName: 'test1'
- job: print
  condition: eq(variables['Build.Reason'], 'PullRequest')
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      echo "tet"
    displayName: 'test'
