# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  variabilaTest: 'valoare'

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging*') }}:
    downloadBranch: 'refs/heads/master'
  ${{ else }}:
    downloadBranch: $(Build.SourceBranch)

trigger:
- master
- next-stable

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo $(downloadBranch)
    echo $(variabilaTest)

  displayName: 'Run a one-line script'
