# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- next-stable
- 20*

pr:
- master
- next-stable
- 20*

jobs:
- job: Test_ceeling
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: true
    clean: true
    persistCredentials: true
  - script: |
      echo "tete"
      cd projects/ad9081
      make
      exit_code=$?
      echo "test2 si $exit_code"
    displayName: 'test1'
- job: print
  condition: eq(variables['Build.Reason'], 'PullRequest')
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      echo "tet"
    displayName: 'test'
