variables:
  var1: $[eq(variables['Build.SourceBranch'], 'refs/heads/no-os_pr')]
  var2: $[eq(variables['System.PullRequest.TargetBranchName'], 'no-os_pr')]

  ${{ if or( eq(variables['Build.SourceBranch'], 'refs/heads/no-os_pr'), eq(variables['System.PullRequest.TargetBranchName'], 'no-os_pr')) }}:
    downloadBranch: 'refs/heads/libiio-v0'
  ${{ elseif or( eq(variables['Build.SourceBranch'], 'refs/heads/next_stable'), eq(variables['System.PullRequest.TargetBranchName'], 'next_stable')) }}:
    downloadBranch: 'refs/heads/next_stable'
  ${{ else }}:
    downloadBranch: 'refs/heads/main'


trigger:
  branches:
    include:
    - main
    - master
    - next_stable
    - no-os_pr

pr:
  branches:
    include:
    - main
    - master
    - next_stable
    - no-os_pr

jobs:
- job: Test_ceeling
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: true
    clean: true
    persistCredentials: true
  - script: |
      echo $(downloadBranch)
      echo $(Build.SourceBranch)
      echo $(System.PullRequest.TargetBranchName)
      echo $(var1)
      echo $(var2)
    displayName: 'Run a one-line script'

- job: print
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      echo Hi
      echo final
    displayName: 'test'
  